Application_web/src/RayzerCoder/UserBundle/Entity/User.php
<?php

namespace RayzerCoder\UserBundle\Entity;

use FOS\UserBundle\Model\User as BaseUser;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="RayzerCoder\UserBundle\Entity\userRepository")
 * @ORM\Table(name="covoitureurs")
 * @ORM\AttributeOverrides({
 *      @ORM\AttributeOverride(name="email",
 *          column=@ORM\Column(
 *              name     = "email",
 *              type     = "string",
 *              length   = 255,
 *              nullable = true
 *          )
 *      ),
 *      @ORM\AttributeOverride(name="password",
 *          column=@ORM\Column(
 *              name     = "mdp",
 *              type     = "string",
 *              length   = 255,
 *              nullable = true
 *          )
 *      ),
 *      @ORM\AttributeOverride(name="username",
 *          column=@ORM\Column(
 *              name     = "nom_utilisateur",
 *              type     = "string",
 *              length   = 255,
 *              nullable = true
 *          )
 *      ),
 * 
 *      @ORM\AttributeOverride(name="confirmationToken",
 *          column=@ORM\Column(
 *              name     = "cle_activation",
 *              type     = "string",
 *              length   = 255,
 *              nullable = true
 *          )
 *      ),
 * @ORM\AttributeOverride(name="lastLogin",
 *          column=@ORM\Column(
 *              name     = "date_derniere_visite",
 *              type     = "datetime",
 *              nullable = true
 *          )
 *      ),
 * 
 * 
 * })
 * 
 * 
 */
class User extends BaseUser {

    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(name="nom", type="string", length=255,nullable=true)
     *
     * @Assert\NotBlank(message="Please enter your first name.", groups={"Registration", "Profile"})
     * @Assert\Length(
     *     min=3,
     *     max="255",
     *     minMessage="The first name is too short.",
     *     maxMessage="The first name is too long.",
     *     groups={"Registration", "Profile"}
     * )
     */
    protected $nom;

    /**
     * @ORM\Column(name="prenom", type="string", length=255, nullable=true)
     *
     * @Assert\NotBlank(message="Please enter your last name.", groups={"Registration", "Profile"})
     * @Assert\Length(
     *     min=3,
     *     max="255",
     *     minMessage="The last name is too short.",
     *     maxMessage="The last name is too long.",
     *     groups={"Registration", "Profile"}
     * )
     */
    protected $prenom;

    /**
     * @ORM\Column(name="sexe", type="string", length=1, nullable=true)
     */
    protected $sexe;

    /**
     * @ORM\Column(name="fumeur", type="integer", nullable=true)
     */
    protected $fumeur;

    /**
     * @ORM\Column(name="date_naissance", type="date", nullable=true)
     */
    protected $date_naissance;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    protected $avatar;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    protected $telephone;

    /**
     * @ORM\Column(name="note", type="integer", length=255, nullable=true, options={"default":0})
     */
    protected $note;

    /**
     * @ORM\Column(name="date_enregistrement", type="datetime", nullable=true)
     */
    protected $date_enregistrement;

    /**
     * @Assert\File(maxSize="500k")
     */
    public $file;

    /**
     * @ORM\Column(name="connecte", type="integer", nullable=true)
     */
    public $connecte;

    /**
     * @ORM\Column(name="longitude", type="float", nullable=true)
     */
    protected $longitude;

    /**
     * @ORM\Column(name="latitude", type="float",  nullable=true)
     */
    protected $latitude;

    /**
     * @ORM\Column(name="skype", type="string",length=255, nullable=true)
     */
    protected $skype;

    /**
     * @ORM\Column(name="facebook", type="string",length=255, nullable=true)
     */
    protected $facebook;
    
    /**
     * @ORM\Column(name="id_facebook", type="string",length=255, nullable=true)
     */
    protected $id_facebook;
    
     /**
     * @ORM\Column(name="etat", type="integer", nullable=true)
     */
    protected $etat;
    

    public function getWebPath() {
        return null === $this->avatar ? null : $this->getUploadDir() . '/' . $this->avatar;
    }

    protected function getUploadRootDir() {
// le chemin absolu du répertoire dans lequel sauvegarder les photos de profil
        return __DIR__ . '/../../../../web/' . $this->getUploadDir();
    }

    protected function getUploadDir() {
// get rid of the __DIR__ so it doesn't screw when displaying uploaded doc/image in the view.
        return 'uploads/pictures';
    }

    public function uploadProfilePicture() {
// Nous utilisons le nom de fichier original, donc il est dans la pratique
// nécessaire de le nettoyer pour éviter les problèmes de sécurité
// move copie le fichier présent chez le client dans le répertoire indiqué.
        $this->file->move($this->getUploadRootDir(), $this->file->getClientOriginalName());

// On sauvegarde le nom de fichier
        $this->avatar = $this->file->getClientOriginalName();

// La propriété file ne servira plus
        $this->file = null;
    }

    public function __construct() {
        parent::__construct();
        $this->note = 0;
        $this->setDateEnregistrement(new \DateTime("now"));
        $this->avatar = "avatar.jpg";
    }

    public function getId() {
        return $this->id;
    }

    public function setId($id) {
        $this->id = $id;
    }

    public function getNom() {
        return $this->nom;
    }

    public function setNom($nom) {
        $this->nom = $nom;
    }

    public function getPrenom() {
        return $this->prenom;
    }

    public function setPrenom($prenom) {
        $this->prenom = $prenom;
    }

    public function getSexe() {
        return $this->sexe;
    }

    public function setSexe($sexe) {
        $this->sexe = $sexe;
    }

    public function getFumeur() {
        return $this->fumeur;
    }

    public function setFumeur($fumeur) {
        $this->fumeur = $fumeur;
    }

    public function getDateNaissance() {
        return $this->date_naissance;
    }

    public function setDateNaissance($date_naissance) {
        $this->date_naissance = $date_naissance;
    }

    public function getAvatar() {
        return $this->avatar;
    }

    public function setAvatar($avatar) {
        $this->avatar = $avatar;
    }

    public function getTelephone() {
        return $this->telephone;
    }

    public function setTelephone($telephone) {
        $this->telephone = $telephone;
    }

    public function getNote() {
        return $this->note;
    }

    public function setNote($note) {
        $this->note = $note;
    }

    public function getDateEnregistrement() {
        return $this->date_enregistrement;
    }

    public function setDateEnregistrement($date_enregistrement) {
        $this->date_enregistrement = $date_enregistrement;
    }

    public function getFile() {
        return $this->file;
    }

    public function setFile($file) {
        $this->file = $file;
    }

    public function getConnecte() {
        return $this->connecte;
    }

    public function setConnecte($connecte) {
        $this->connecte = $connecte;
    }

    public function getLongitude() {
        return $this->longitude;
    }

    public function setLongitude($longitude) {
        $this->longitude = $longitude;
    }

    public function getLatitude() {
        return $this->latitude;
    }

    public function setLatitude($latitude) {
        $this->latitude = $latitude;
    }

    public function getSkype() {
        return $this->skype;
    }

    public function setSkype($skype) {
        $this->skype = $skype;
    }

    public function getFacebook() {
        return $this->facebook;
    }

    public function setFacebook($facebook) {
        $this->facebook = $facebook;
    }

    public function getIdFacebook() {
        return $this->id_facebook;
    }

    public function setIdFacebook($id_facebook) {
        $this->id_facebook = $id_facebook;
    }
    public function getEtat() {
        return $this->etat;
    }

    public function setEtat($etat) {
        $this->etat = $etat;
    }




}

Application_web/src/RayzerCoder/UserBundle/Controller/DefaultController.php
<?php

namespace RayzerCoder\UserBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use RayzerCoder\UserBundle\Form\Type\UserRechercheFormType;
use RayzerCoder\UserBundle\Form\Type\SimpleRechercheFormType;
use RayzerCoder\UserBundle\Form\IdentityPictureType;
use RayzerCoder\UserBundle\Form\Type\EvaluerFormType;
use Front\MNRSBundle\Entity\Evaluations;

class DefaultController extends Controller {

    public function indexAction() {
        return $this->render('RayzerCoderUserBundle:Default:index.html.twig', array());
    }

    public function showAction() {
        $user = $this->container->get('security.context')->getToken()->getUser();
        if (!is_object($user) || !$user instanceof UserInterface) {
            throw new AccessDeniedException('This user does not have access to this section.');
        }
        return $this->container->get('templating')->renderResponse('RayzerCoderUserBundle:Default:show.html.' . $this->container->getParameter('fos_user.template.engine'), array('user' => $user));
    }

    public function showUserAction($id) {

        $requete = $this->get('request');

        if (($requete->getMethod() == 'POST')) {
            $formshow = 0;
            $em = $this->getDoctrine()->getManager();
            $user = $em->getRepository('RayzerCoderUserBundle:User')->find($id);
            $note = $user->getNote() + $_POST['rating'];
            $user->setNote($note);
            $qb = $em->createQueryBuilder();
            $q = $qb->update('RayzerCoderUserBundle:User', 'u')
                    ->set('u.note', '?1')
                    ->where('u.id = ?2')
                    ->setParameter(1, $note)
                    ->setParameter(2, $id)
                    ->getQuery();
            $p = $q->execute();

            $evaluation = new Evaluations();

            $covoiturage = $em->getRepository('FrontMNRSBundle:Covoiturages')->find(1);
            $evaluation->setNote($_POST['rating']);
            $evaluation->setMessage($_POST['rating']);
            $evaluation->setIdEvaluateur($this->getUser());
            $evaluation->setIdCovoiturage($covoiturage);

            $em->persist($evaluation);
            $em->flush();







//            $queryBuilder = $em->createQueryBuilder();
//    $queryBuilder
//        ->update('RayzerCoder\UserBundle\Entity\User', 'u')
//        ->set('u.rating', 5)
//        ->where($queryBuilder->expr()->eq('u.id', $id));
//    $p = $queryBuilder->execute();  
//            $request = $this->getRequest();
//            $rating = $this->getRequest()->query->get('rating');
//            $commentaire = $request->query->get('commentaire');



            return $this->render('RayzerCoderUserBundle:Default:show.html.twig', array('user' => $user, 'formshow' => $formshow));
        } else {

            $formshow = 1;
            $em = $this->getDoctrine()->getManager();
            $user = $em->getRepository('RayzerCoderUserBundle:User')->find($id);
            $form = $this->createForm(new EvaluerFormType());
            if ($user == null) {
                $user = $this->container->get('security.context')->getToken()->getUser();
                if (!is_object($user) || !$user instanceof UserInterface) {
                    throw new AccessDeniedException('This user does not have access to this section.');
                }
            }

            return $this->render('RayzerCoderUserBundle:Default:show.html.twig', array('user' => $user, 'formshow' => $formshow));
        }
    }

    public function rechercheAction() {
        $form = $this->createForm(new UserRechercheFormType());
        $request = $this->getRequest();
        if ($request->getMethod() == 'POST') {
            $form->bind($request);

            //On vérifie que les valeurs entrées sont correctes
            if ($form->isValid()) {
                $em = $this->getDoctrine()->getManager();

                //On récupère les données entrées dans le formulaire par l'utilisateur
                $data = $this->getRequest()->request->get('rayzer_coder_userbundle_userrecherche');

                //On va récupérer la méthode dans le repository afin de trouver toutes les annonces filtrées par les paramètres du formulaire
                $liste_users = $em->getRepository('RayzerCoderUserBundle:User')->findUserByParametres($data);

                //Puis on redirige vers la page de visualisation de cette liste d'annonces
                return $this->render('RayzerCoderUserBundle:Default:resultatRecherche.html.twig', array('liste_users' => $liste_users));
            }
        }

        // À ce stade :
        // - Soit la requête est de type GET, donc le visiteur vient d'arriver sur la page et veut voir le formulaire
        // - Soit la requête est de type POST, mais le formulaire n'est pas valide, donc on l'affiche de nouveau
        return $this->render('RayzerCoderUserBundle:Default:rechercheUser.html.twig', array('form' => $form->createView()));
    }

    public function simpleRechercheAction() {
        $form = $this->createForm(new SimpleRechercheFormType());
        $request = $this->getRequest();
        if ($request->getMethod() == 'POST') {
            $form->bind($request);

            //On vérifie que les valeurs entrées sont correctes
            if ($form->isValid()) {
                $em = $this->getDoctrine()->getManager();

                //On récupère les données entrées dans le formulaire par l'utilisateur
                $data = $this->getRequest()->request->get('rayzer_coder_userbundle_simplerecherche');

                //On va récupérer la méthode dans le repository afin de trouver toutes les annonces filtrées par les paramètres du formulaire
                $liste_users = $em->getRepository('RayzerCoderUserBundle:User')->findUserByParametre($data);

                //Puis on redirige vers la page de visualisation de cette liste d'annonces
                return $this->render('RayzerCoderUserBundle:Default:resultatRecherche.html.twig', array('liste_users' => $liste_users));
            }
        }

        // À ce stade :
        // - Soit la requête est de type GET, donc le visiteur vient d'arriver sur la page et veut voir le formulaire
        // - Soit la requête est de type POST, mais le formulaire n'est pas valide, donc on l'affiche de nouveau
        return $this->render('RayzerCoderUserBundle:Default:rechercheUser.html.twig', array('form' => $form->createView()));
    }

    public function editAvatarAction() {
        $usr = $this->getUser();

        $form = $this->createForm(new IdentityPictureType(), $usr);

        if ($this->getRequest()->getMethod() === 'POST') {
            $form->bind($this->getRequest());
            if ($form->isValid()) {
                $em = $this->getDoctrine()->getEntityManager();

                $usr->uploadProfilePicture();

                $em->persist($usr);
                $em->flush();

                $this->redirect($this->generateUrl('fos_user_profile_show'));
            }
        }

        return $this->render('RayzerCoderUserBundle:Default:editAvatar.html.twig', array(
                    'user' => $usr,
                    'form' => $form->createView()
                        )
        );
    }

}

Application_web/src/RayzerCoder/UserBundle/Resources/views/Default/editAvatar.html.twig
{% extends "RayzerCoderUserBundle::layout.html.twig" %}
{% block content %}




<div style="height:500px;" class="shadow main container round" id="contenu">



    <div class="content-wrapper">

        <div class="thirty laurel">
            <div class="shadow shut-in gd-eee profil-box padd-half no-dist">
                <h2 class="gd-1 padd-half ns nc"> <span class="uc"></span> &nbsp;</h2>

                <div class="avatar-container-box">
                    <div class="avatar-box bd bg-fff bd-ccc left">
                        <div class="js-ajax-update-avatar" style="height: 75px;">


    {% if user.avatar %}
                            <img class="avatar" alt="Avatar - {{ 'profile.show.username'|trans }}:{{ user.username }}" title="{{ user.username }}"src="{{ asset(user.getWebPath()) }}">      </div>
                       {% else %}
                        Pas d'image de profil chargée !
{% endif %}


                        <a href="/fr/mon-compte/mon-profil/mon-avatar" id="js-ajaxform-edit-avatar" class="edit-link no-hover bg-000 cl-fff alpha-70 nc no-wrap"><ins class="icon edit-small"></ins>&nbsp;Modifier</a>
                    </div>

                    <h2 class="vanilla nick cl-5 nc ns">{{ user.username }}</h2>
                </div>

            </div>

            <div class="shadow gd-8 no-padd shut-nav">
                <ul class="vanilla bd bd-eee">
                    <li>

{% if user.avatar %}
                        <img style="width:150px; height: 150px" src="{{ asset(user.getWebPath()) }}" />
{% else %}
                        Pas d'image de profil chargée !
{% endif %}

                        <h1>Charger une image de profil</h1>

                        <form action="#" method="post" {{ form_enctype(form) }}>
    {{ form_widget(form) }}
                                <input type="submit" value="Uploader" />
                            </form>


                        </li>
                    </ul>
                </div>
                <div class="shadow gd-eee shut-in">
                    <div class="bg-fff padd-half bd bd-ccc rating-box round">
                        <span class="nc">évaluations :</span>
                        <div class="rating right" id="js-ajax-update-rating">
                            <p class="txt-ctr"><abbr title="non-applicable">{{user.note}}</abbr></p><p>
                            </p></div>
                        <div class="clear"></div>
                    </div>  </div>



            </div>
            <div class="seventy hardy">



                <h3>Bienvenue sur le profil de l'utilisateur {{ user.username }}</h3>

                <div class="clear"></div>
                <div class="seventy hardy">



                    <div class="clear"></div>



                    <h4>Nom utilisateur : {{user.username}} </h4>

                    <h4>Nom : {{user.nom}}</h4>
                    <h4>Prenom : {{user.prenom}}</h4>
                    <h4>Sexe :{% if user.sexe == "h" %}Homme{% else %}Femme{% endif %}</h4>

                    <h4>Date de naissance {{user.dateNaissance|date('d/m/Y')}}</h4>

                    <h4>Date d'inscription {{user.dateEnregistrement|date('d/m/Y')}}</h4>

                    <h4>Numero Telephone {{user.telephone}}</h4>
                    <div class="clear"></div>
                </div>
            {{ form(form) }}
            </div>




            <div class="clear"></div>

            <div id="main-nav-outer">
                <div id="navigation">
                    <ul id="main-nav" class="vanilla">
                        <li class="nav-item"><a class="nav-link" rel="home" title="Accueil" href="{{ path("covoiturage_accueil") }}">Accueil</a></li>{% if is_granted("IS_AUTHENTICATED_REMEMBERED") %}<li class="nav-item"><a class="nav-link" title="Mon Profile" href="{{ path('fos_user_profile_show') }}">Mon Profile</a></li>{% endif %} 
                        <li class="nav-item"><a class="nav-link" rel="recherche" title="Recherche" href="{{ path("rayzer_coder_user_simple_search") }}">Recherche Covoitureur</a></li>
                        <li class="nav-item"><a class="nav-link" rel="recherche" title="Recherche" href="{{ path("rayzer_coder_user_advanced_search") }}">Recherche Avancée</a></li>

                        <li class="nav-item"><a class="nav-link" rel="contents" title="Les trajets" href="#">Les trajets</a></li>
                        <li class="nav-item"><a class="nav-link" title="La charte" href="{{ path("covoiturage_laCharte") }}">La charte</a></li>
                        <li class="nav-item"><a class="nav-link" title="FAQ" href="{{ path("covoiturage_faq") }}">FAQ</a></li>
                        <li class="nav-item"><a class="nav-link" title="Réclamations" href="{{ path("covoiturage_reclamation") }}">Réclamation</a></li>{% if is_granted("IS_AUTHENTICATED_REMEMBERED") %}<li class="nav-item"><a class="nav-link" title="Déconnecter" href="{{ path('fos_user_security_logout') }}">Déconnecter</a></li>{% else %}<li class="nav-item"><a class="nav-link" title="Déconnecter" href="{{ path('fos_user_security_login') }}">S'authentifier</a></li>{% endif %}

                    



                        </ul>
                    </div>
                </div>          <a href="#contenu" title="Revenir au contenu">
                    <ins class="icon blue-car js-car" id="car-1" style="top: 75px;"></ins>
                    <ins class="icon green-car js-car" id="car-2" style="top: 89px;"></ins>
                    <ins class="icon pink-car js-car" id="car-3" style="top: 84px;"></ins>
                </a>
            </div>
        </div>

























                {% endblock %}

Application_web/src/RayzerCoder/UserBundle/Resources/views/Default/rechercheUser.html.twig


{% extends "RayzerCoderUserBundle::layout.html.twig" %}

                {% block content %}

<div class="shadow main container round" id="contenu">



    <div class="content-wrapper">

        <div class="thirty laurel">
      

        </div>
        <div class="seventy hardy">



            <h3></h3>

            <div class="clear"></div>




            <div class="well research_form">
                <h3>Recherche un utilisateur</h3>

                <form method="post" {{ form_enctype(form) }}>
        {{ form_widget(form) }}
                    <input type="submit" />
                </form>
            </div>

            <div class="clear"></div>
        </div>
    </div>
    <div class="right-wrapper">


        <!-- No add, probably a Google one -->
      
    </div>
    <div class="clear"></div>

    <div id="main-nav-outer">
         <div id="navigation">
               <ul id="main-nav" class="vanilla">
                    <li class="nav-item"><a class="nav-link" rel="home" title="Accueil" href="{{ path("covoiturage_accueil") }}">Accueil</a></li>{% if is_granted("IS_AUTHENTICATED_REMEMBERED") %}<li class="nav-item"><a class="nav-link" title="Mon Profile" href="{{ path('fos_user_profile_show') }}">Mon Profile</a></li>{% endif %} 
                     <li class="nav-item"><a class="nav-link" rel="recherche" title="Recherche" href="{{ path("rayzer_coder_user_simple_search") }}">Recherche Covoitureur</a></li>
                    <li class="nav-item"><a class="nav-link" rel="recherche" title="Recherche" href="{{ path("rayzer_coder_user_advanced_search") }}">Recherche Avancée</a></li>
                  
                     <li class="nav-item"><a class="nav-link" rel="contents" title="Les trajets" href="#">Les trajets</a></li>
                    <li class="nav-item"><a class="nav-link" title="La charte" href="{{ path("covoiturage_laCharte") }}">La charte</a></li>
                    <li class="nav-item"><a class="nav-link" title="FAQ" href="{{ path("covoiturage_faq") }}">FAQ</a></li>
                    <li class="nav-item"><a class="nav-link" title="Réclamations" href="{{ path("covoiturage_reclamation") }}">Réclamation</a></li>{% if is_granted("IS_AUTHENTICATED_REMEMBERED") %}<li class="nav-item"><a class="nav-link" title="Déconnecter" href="{{ path('fos_user_security_logout') }}">Déconnecter</a></li>{% else %}<li class="nav-item"><a class="nav-link" title="Déconnecter" href="{{ path('fos_user_security_login') }}">S'authentifier</a></li>{% endif %}
                </ul>
            </div>
    </div>          <a href="#contenu" title="Revenir au contenu">
        <ins class="icon blue-car js-car" id="car-1" style="top: 157px;"></ins>
        <ins class="icon green-car js-car" id="car-2" style="top: 52px;"></ins>
        <ins class="icon pink-car js-car" id="car-3" style="top: 64px;"></ins>
    </a>
</div>
                {% endblock %}  










































































Application_web/src/RayzerCoder/UserBundle/Resources/views/Default/resultatRecherche.html.twig
{% extends "RayzerCoderUserBundle::layout.html.twig" %}

                {% block content %}

<div class="shadow main container round" id="contenu">



    <div class="content-wrapper">

        
        <div class="seventy hardy">



            <div class="clear"></div>


<div >
    <h3>Resultat Recherche</h3>

    <ul>
            {% for user in liste_users %}
        <li><a href="{{ path('rayzer_coder_user_show', {'id': user.id}) }}">{{user.username}}</a></li>
            {% else %}
        <p>Désolé il n'y a, pour le moment, aucune annonce correspondant à votre recherche.</p>
            {% endfor %}
    </ul>

</div>



            <div class="content-menu">
              
            </div>
            <div class="clear"></div>
        </div>
    </div>
    
    <div class="clear"></div>

    <div id="main-nav-outer">
        <div id="navigation">
               <ul id="main-nav" class="vanilla">
                    <li class="nav-item"><a class="nav-link" rel="home" title="Accueil" href="{{ path("covoiturage_accueil") }}">Accueil</a></li>{% if is_granted("IS_AUTHENTICATED_REMEMBERED") %}<li class="nav-item"><a class="nav-link" title="Mon Profile" href="{{ path('fos_user_profile_show') }}">Mon Profile</a></li>{% endif %} 
                     <li class="nav-item"><a class="nav-link" rel="recherche" title="Recherche" href="{{ path("rayzer_coder_user_simple_search") }}">Recherche Covoitureur</a></li>
                    <li class="nav-item"><a class="nav-link" rel="recherche" title="Recherche" href="{{ path("rayzer_coder_user_advanced_search") }}">Recherche Avancée</a></li>
                  
                     <li class="nav-item"><a class="nav-link" rel="contents" title="Les trajets" href="#">Les trajets</a></li>
                    <li class="nav-item"><a class="nav-link" title="La charte" href="{{ path("covoiturage_laCharte") }}">La charte</a></li>
                    <li class="nav-item"><a class="nav-link" title="FAQ" href="{{ path("covoiturage_faq") }}">FAQ</a></li>
                    <li class="nav-item"><a class="nav-link" title="Réclamations" href="{{ path("covoiturage_reclamation") }}">Réclamation</a></li>{% if is_granted("IS_AUTHENTICATED_REMEMBERED") %}<li class="nav-item"><a class="nav-link" title="Déconnecter" href="{{ path('fos_user_security_logout') }}">Déconnecter</a></li>{% else %}<li class="nav-item"><a class="nav-link" title="Déconnecter" href="{{ path('fos_user_security_login') }}">S'authentifier</a></li>{% endif %}
                </ul>
            </div>
    </div>          <a href="#contenu" title="Revenir au contenu">
        <ins class="icon blue-car js-car" id="car-1" style="top: 157px;"></ins>
        <ins class="icon green-car js-car" id="car-2" style="top: 52px;"></ins>
        <ins class="icon pink-car js-car" id="car-3" style="top: 64px;"></ins>
    </a>
</div>
                {% endblock %}  


























































Application_web/src/RayzerCoder/UserBundle/Resources/views/Default/show_content.html.twig
{% trans_default_domain 'FOSUserBundle' %}

<div class="fos_user_user_show">
    <p>{{ 'profile.show.username'|trans }}: {{ user.username }}</p>
    <p>{{ 'profile.show.email'|trans }}: {{ user.email }}</p>
</div>